import {StyleSheet, Dimensions, Platform} from 'react-native';
import Colors from '../../Res/Colors';
import Fonts from '../../Res/Fonts';

const IS_IOS = Platform.OS === 'ios';
const IS_ANDROID = Platform.OS === 'android';
const {width: viewportWidth, height: viewportHeight} = Dimensions.get('window');

export default StyleSheet.create({
  viewcontainer: {
    flex: 1,
    backgroundColor: Colors.theme,
  },
  headerRowStyle: {
    flexDirection: 'row',
    height: IS_IOS ? 44 : 55,
    backgroundColor: Colors.theme,
  },
  backImageBack: {
    height: 30,
    width: 30,
    marginHorizontal: 15,
    backgroundColor: 'transparent',
    borderRadius: 20,
    justifyContent: 'center',
    alignSelf: 'center',
  },
  backImageStyle: {
    height: 20,
    width: 20,
    alignSelf: 'center',
    tintColor: Colors.white,
  },
  heartImageBack: {
    height: 30,
    width: 30,
    marginStart: 5,
    backgroundColor: 'transparent',
    borderRadius: 20,
    justifyContent: 'center',
    alignSelf: 'center',
  },
  titleText: {
    flex: 1,
    fontSize: 20,
    alignSelf: 'center',
    fontFamily: Fonts.MontserratMedium,
    color: Colors.white,
  },
  viewStyle: {
    flex: 1,
    backgroundColor: Colors.offWhite,
  },

  emptyView: {
    height: viewportHeight - 50,
    width: viewportWidth,
    justifyContent: 'center',
    backgroundColor: Colors.white,
  },
  ImageStyle: {
    height: 100,
    width: 100,
    alignSelf: 'center',
    tintColor: Colors.grey,
  },
  EmptyText: {
    fontSize: 14,
    marginTop: 15,
    fontFamily: Fonts.MontserratRegular,
    textAlign: 'center',
    color: Colors.grey,
  },

  rowContainer: {
    height: 165,
    width: viewportWidth - 15,
    margin: 10,
    alignSelf: 'center',
    flexDirection: 'row',
    borderRadius: 10,
    shadowColor: Colors.black,
    shadowOpacity: 0.3,
    shadowRadius: 8,
    shadowOffset: {width: 0, height: 0},
    elevation: 5,
    backgroundColor: Colors.white,
  },
  rowImageStyle: {
    height: 165,
    width: 130,
    borderTopLeftRadius: 10,
    borderBottomLeftRadius: 10,
  },
  rowIconStyle: {
    height: 15,
    width: 15,
    alignSelf: 'center',
    marginEnd: 5,
  },
  detailViewStyle: {
    flex: 1,
    marginHorizontal: 10,
    justifyContent: 'center',
  },
  rowViewStyle: {
    marginTop: 5,
    marginEnd: 5,
    flexDirection: 'row',
    alignItems: 'center',
  },
  nameTextStyle: {
    fontSize: 16,
    fontFamily: Fonts.MontserratBold,
    color: Colors.black,
  },
  typeTextStyle: {
    fontSize: 13,
    fontFamily: Fonts.MontserratMedium,
    color: Colors.grey,
    marginTop: 5,
  },
  boldTextStyle: {
    fontSize: 14,
    fontFamily: Fonts.MontserratBold,
    color: Colors.black,
    marginEnd: 10,
  },
  lightTextStyle: {
    fontSize: 12,
    fontFamily: Fonts.MontserratMedium,
    color: Colors.grey,
    alignSelf: 'center',
  },
  priceTextStyle: {
    flex: 1,
    fontSize: 14,
    fontFamily: Fonts.MontserratBold,
    color: Colors.black,
  },

  descTextStyle: {
    fontSize: 14,
    fontFamily: Fonts.MontserratRegular,
    color: Colors.black,
    marginVertical: 5,
    marginHorizontal: 15,
  },

  socialViewStyle: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 10,
    marginHorizontal: 10,
  },
  socialConatiner: {
    height: 30,
    width: 30,
    marginEnd: 10,
    backgroundColor: 'transparent',
    borderRadius: 20,
    alignSelf: 'center',
  },
  socialImageStyle: {
    height: 25,
    width: 25,
    alignSelf: 'center',
    //tintColor: Colors.black,
  },

  btnContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 10,
    marginHorizontal: 10,
  },
  tipContainer: {
    flex: 1,
    justifyContent: 'center',
    height: 40,
    marginEnd: 10,
    borderRadius: 5,
    backgroundColor: Colors.theme,
    shadowColor: Colors.black,
    shadowOpacity: 0.3,
    shadowRadius: 8,
    shadowOffset: {width: 0, height: 0},
    elevation: 5,
  },
  tipText: {
    fontSize: 14,
    fontFamily: Fonts.MontserratMedium,
    alignSelf: 'center',
    color: Colors.white,
  },
  hireContainer: {
    flex: 1,
    justifyContent: 'center',
    height: 40,
    marginEnd: 10,
    borderRadius: 5,
    backgroundColor: Colors.white,
    shadowColor: Colors.black,
    shadowOpacity: 0.3,
    shadowRadius: 8,
    shadowOffset: {width: 0, height: 0},
    elevation: 5,
  },
  hireText: {
    fontSize: 14,
    fontFamily: Fonts.MontserratMedium,
    alignSelf: 'center',
    color: Colors.black,
  },
  scheduleContainer: {
    flex: 1,
    justifyContent: 'center',
    height: 40,
    borderRadius: 5,
    backgroundColor: Colors.black,
    shadowColor: Colors.black,
    shadowOpacity: 0.3,
    shadowRadius: 8,
    shadowOffset: {width: 0, height: 0},
    elevation: 5,
  },
  scheduleText: {
    fontSize: 12,
    fontFamily: Fonts.MontserratMedium,
    alignSelf: 'center',
    textAlign: 'center',
    color: Colors.white,
  },

  galleryViewStyle: {
    width: viewportWidth - 15,
    margin: 5,
    alignSelf: 'center',
    backgroundColor: Colors.white,
    borderRadius: 10,
    shadowColor: Colors.black,
    shadowOpacity: 0.3,
    shadowRadius: 8,
    shadowOffset: {width: 0, height: 0},
    elevation: 5,
  },
  galleryTextStyle: {
    fontSize: 15,
    fontFamily: Fonts.MontserratSemiBold,
    marginVertical: 10,
    marginStart: 10,
    color: Colors.black,
  },
  galleryContainer: {
    height: 100,
    margin: 5,
    justifyContent: 'center',
  },
  galleryImageStyle: {
    height: 100,
    width: viewportWidth / 3 - 15,
    borderRadius: 5,
  },
  galleryPlayImage: {
    height: 30,
    width: 30,
    alignSelf: 'center',
    tintColor: Colors.white,
    position: 'absolute',
  },
  emptyGalleryText: {
    fontSize: 14,
    fontFamily: Fonts.MontserratSemiBold,
    marginVertical: 20,
    alignSelf: 'center',
    color: Colors.grey,
  },
});
