import {StyleSheet, Dimensions, Platform} from 'react-native';
import Colors from '../../Res/Colors';
import Fonts from '../../Res/Fonts';

const IS_IOS = Platform.OS === 'ios';
const IS_ANDROID = Platform.OS === 'android';
const {width: viewportWidth, height: viewportHeight} = Dimensions.get('window');

export default StyleSheet.create({
  viewcontainer: {
    flex: 1,
    backgroundColor: Colors.theme,
  },
  headerRowStyle: {
    flexDirection: 'row',
    height: IS_IOS ? 44 : 55,
    backgroundColor: Colors.offWhite,
  },
  backImageBack: {
    height: 40,
    width: 20,
    marginHorizontal: 10,
    backgroundColor: 'transparent',
    borderRadius: 20,
    justifyContent: 'center',
    alignSelf: 'center',
  },
  backImageStyle: {
    height: 20,
    width: 20,
    alignSelf: 'center',
    tintColor: Colors.black,
  },
  titleRowContainer: {
    flex: 1,
    flexDirection: 'row',
    marginStart: 10,
    // marginEnd: 45,
  },
  titleImage: {
    height: 15,
    width: 15,
    alignSelf: 'center',
  },
  titleText: {
    fontSize: 16,
    marginHorizontal: 10,
    alignSelf: 'center',
    fontFamily: Fonts.MontserratSemiBold,
    color: Colors.black,
  },
  noMap: {flex: 1, alignItems: 'center'},
  viewStyle: {
    flex: 1,
    backgroundColor: Colors.offWhite,
  },
  userImageStyle: {
    height: 42,
    width: 42,
    borderRadius: 100,
    borderWidth: 2,
  },
  MapContainer: {
    flex: 1,
    width: viewportWidth,
    height: viewportHeight,
    justifyContent: 'center',
    borderWidth: 0.3,
    borderColor: Colors.grey,
  },
  map: {
    // ...StyleSheet.absoluteFillObject,
    flex: 1,
  },
  listContainer: {
    //flex: 0.9,
    //height: 240,
    flexDirection: 'column',
  },
  listHeadRow: {
    flexDirection: 'row',
    justifyContent: 'center',
  },
  listHeadText: {
    flex: 1,
    fontSize: 16,
    fontFamily: Fonts.MontserratSemiBold,
    color: Colors.black,
    marginStart: 10,
    marginVertical: 10,
  },
  listSubText: {
    fontSize: 14,
    fontFamily: Fonts.MontserratMedium,
    color: Colors.grey,
    marginEnd: 15,
    alignSelf: 'center',
  },

  fabViewStyle: {
    position: 'absolute',
    flex: 1,
    //top: 10,
    bottom: 0,
    alignSelf: 'flex-end',
    justifyContent: 'space-between',
  },
  fabBtnStyle: {
    width: 45,
    height: 45,
    borderRadius: 25,
    marginBottom: 10,
    marginEnd: 10,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Colors.theme,
  },
  fabIconStyle: {
    width: 20,
    height: 20,
    tintColor: Colors.white,
  },

  emptyLocation: {
    position: 'absolute',
    height: viewportHeight - 50,
    width: viewportWidth,
    justifyContent: 'center',
    backgroundColor: Colors.blackTrans,
  },
  emptyTxtLoc: {
    fontSize: 16,
    fontFamily: Fonts.MontserratSemiBold,
    textAlign: 'center',
    color: Colors.white,
  },
  emptyBtnContainer: {
    marginHorizontal: 20,
    marginTop: 20,
    marginBottom: 20,
    height: 40,
    width: 150,
    backgroundColor: Colors.theme,
    justifyContent: 'center',
    alignSelf: 'center',
    borderRadius: 5,
  },
  emptyBtnText: {
    fontSize: 16,
    fontFamily: Fonts.MontserratMedium,
    color: Colors.white,
    alignSelf: 'center',
  },

  emptyView: {
    height: viewportHeight - 50,
    width: viewportWidth,
    justifyContent: 'center',
    backgroundColor: Colors.white,
  },
  ImageStyle: {
    height: 100,
    width: 100,
    alignSelf: 'center',
    tintColor: Colors.grey,
  },
  EmptyText: {
    fontSize: 14,
    marginTop: 15,
    fontFamily: Fonts.MontserratRegular,
    textAlign: 'center',
    color: Colors.grey,
  },

  rowContainer: {
    height: 120,
    width: viewportWidth - 15,
    margin: 5,
    flexDirection: 'row',
    borderRadius: 10,
    shadowColor: Colors.black,
    shadowOpacity: 0.3,
    shadowRadius: 8,
    shadowOffset: {width: 0, height: 0},
    elevation: 5,
    backgroundColor: Colors.white,
  },
  rowImageStyle: {
    height: 120,
    width: 120,
    borderTopLeftRadius: 10,
    borderBottomLeftRadius: 10,
  },
  detailViewStyle: {
    flex: 1,
    margin: 10,
    justifyContent: 'center',
  },
  rowViewStyle: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
  },
  endRowViewStyle: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  nameTextStyle: {
    flex: 1,
    fontSize: 16,
    fontFamily: Fonts.MontserratBold,
    color: Colors.black,
  },
  mileTextStyle: {
    fontSize: 12,
    fontFamily: Fonts.MontserratMedium,
    color: Colors.grey,
  },
  descTextStyle: {
    fontSize: 14,
    fontFamily: Fonts.MontserratRegular,
    color: Colors.black,
    marginVertical: 5,
  },
  typePriceTextStyle: {
    fontSize: 14,
    fontFamily: Fonts.MontserratBold,
    color: Colors.black,
  },
  likeImageStyle: {
    height: 15,
    width: 15,
  },
  likeTextStyle: {
    fontSize: 12,
    fontFamily: Fonts.MontserratMedium,
    color: Colors.black,
    marginStart: 3,
  },

  eventRowContainer: {
    width: viewportWidth / 2 - 10,
    margin: 5,
    borderRadius: 10,
    shadowColor: Colors.black,
    shadowOpacity: 0.3,
    shadowRadius: 8,
    shadowOffset: {width: 0, height: 4},
    elevation: 5,
    backgroundColor: Colors.white,
  },
  eventImageStyle: {
    height: 110,
    width: viewportWidth / 2 - 10,
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
  },
  eventDetailView: {
    margin: 10,
    justifyContent: 'center',
  },
  eventNameText: {
    fontSize: 14,
    fontFamily: Fonts.MontserratBold,
    color: Colors.black,
  },
  eventDescText: {
    fontSize: 12,
    fontFamily: Fonts.MontserratRegular,
    color: Colors.black,
    marginVertical: 5,
  },

  sheet_headContainer: {
    borderTopStartRadius: 25,
    borderTopEndRadius: 25,
    paddingVertical: 10,
    paddingHorizontal: 20,
  },
  sheet_title_text: {
    fontSize: 18,
    color: Colors.black,
    fontFamily: Fonts.MontserratSemiBold,
    alignSelf: 'center',
  },
  sheet_head_text: {
    fontSize: 16,
    color: Colors.black,
    fontFamily: Fonts.MontserratSemiBold,
    marginTop: 10,
    marginEnd: 5,
  },
  sheet_list_style: {
    alignSelf: 'center',
    marginVertical: 10,
    //height: 150,
  },
  sliderStyle: {
    width: viewportWidth - 30,
    height: 45,
    alignSelf: 'center',
  },
  thumbStyle: {
    height: 15,
    width: 15,
    borderRadius: 10,
    backgroundColor: Colors.theme,
  },
  railStyle: {
    flex: 1,
    height: 2,
    backgroundColor: Colors.grey,
  },
  railColorStyle: {
    flex: 1,
    height: 2.5,
    backgroundColor: Colors.theme,
  },
  labelContainer: {
    paddingVertical: 2,
    paddingHorizontal: 8,
    backgroundColor: Colors.theme,
    borderRadius: 5,
  },
  labelStyle: {
    fontSize: 11,
    color: Colors.white,
    fontFamily: Fonts.MontserratMedium,
  },
  dividerViewStyle: {
    height: 1,
    width: viewportWidth,
    backgroundColor: Colors.grey,
  },
  distanceRowContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  distanceRowText: {
    fontSize: 11,
    color: Colors.grey,
    fontFamily: Fonts.MontserratSemiBold,
  },
  btnContainer: {
    height: 40,
    width: viewportWidth / 3 - 20,
    marginVertical: 5,
    marginHorizontal: 3,
    borderColor: Colors.black,
    borderWidth: 1,
    borderRadius: 20,
    backgroundColor: Colors.white,
    justifyContent: 'center',
  },
  btnActiveContainer: {
    height: 40,
    width: viewportWidth / 3 - 20,
    marginVertical: 5,
    marginHorizontal: 3,
    borderColor: Colors.theme,
    borderWidth: 1,
    borderRadius: 20,
    backgroundColor: Colors.theme,
    justifyContent: 'center',
  },
  btnText: {
    fontSize: 14,
    fontFamily: Fonts.MontserratMedium,
    color: Colors.black,
    alignSelf: 'center',
  },
  btnActiveText: {
    fontSize: 14,
    fontFamily: Fonts.MontserratMedium,
    color: Colors.white,
    alignSelf: 'center',
  },

  btnViewContainer: {
    height: 45,
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginHorizontal: 20,
  },
  resetContainer: {
    //flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    width: 120,
    backgroundColor: Colors.boxgrey,
    borderRadius: 10,
  },
  resetText: {
    fontSize: 15,
    fontFamily: Fonts.MontserratMedium,
    alignSelf: 'center',
    color: Colors.black,
  },
  applyContainer: {
    // flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    width: 120,
    backgroundColor: Colors.black,
    borderRadius: 10,
  },
  applyText: {
    fontSize: 15,
    fontFamily: Fonts.MontserratMedium,
    alignSelf: 'center',
    color: Colors.white,
  },
});
