const constants = { 
  // baseUrl: 'https://projects.webbycentral.xyz/WC716/public/api/',
  // baseUrl: 'http://18.224.13.122/public/api/',
  // baseUrl: 'http://192.168.10.10:8080/api/',
  // baseUrl: 'https://app.busk-it.com/api/',
  baseUrl: 'https://ryan.vorksol.com/api/',

  // paypalBaseUrl:'www.sandbox.paypal.com/',///sandbox url for testing paypal
  paypalBaseUrl:'www.paypal.com/',//Live url
  // paypalRedirectUrl:'https://example.com/return',//sandbox return url of paypal
  paypalRedirectUrl:'https://app.busk-it.com/return',//live return url of paypal

  // paypalRedirectCancelUrl:'https://example.com/cancel',//sandbox return cancel url of paypal
  paypalRedirectCancelUrl:'https://app.busk-it.com/cancel',//sandbox return cancel url of paypal
  api: {
    login: 'login',
    registration: 'sign-up',
    socialLogin: 'check-social-login',
    sendOTP: 'send-otp',
    verifyOTP: 'otp-verify',
    forgotVerify: 'forgot-password-verify',
    forgotPassword: 'forgot-password',
    resetPassowrd: 'reset-password',
    getUser: 'user-detail',
    getBusker: 'busker-details',
    getBuskerDetail: 'user-busker-details',
    userUpdateProfile: 'user-update-profile',
    buskerUpdateProfile: 'busker-update-profile',
    changePassword: 'change-password',
    updateLocation: 'update-location',
    cmsPage: 'cms-page-byId',
    contactUs: 'contact-us',
    blogList: 'blog-list',
    blogDetails: 'blog-details',
    genreList: 'busker-genres-list',
    buskerMapList: 'get-map-busker',
    buskerNearList: 'busker-list',
    eventNearList: 'nearest-events-list',
    addFavorite: 'add-to-favorite',
    favoriteList: 'favorite-busker-list',
    findBusker: 'find-busker-event',
    tipsDetail: 'busker-payout-detail',
    tipsList: 'busker-all-tips-recieved',
    tipsSentList: 'user-all-tips-sent',
    tipsThanks: 'thanks-tip-message',
    tipPayout: 'busker-total-payout',
    tipPayoutDetail: 'busker-payout-users-detail',
    userFavBuskerEvents: 'fav-busker-event-list',
    userEvents: 'user-event-hire-list',
    userEventDetails: 'user-event-details',
    buskerEvents: 'busker-events',
    buskerEventDetails: 'busker-event-details',
    buskerNewEvent: 'add-new-event',
    buskerFanList: 'busker-fan-list',
    buskerFanDelete: 'delete-busker-fan',
    buskerGallery: 'busker-gallery',
    buskerUpload: 'upload-data',
    buskerGalleryDelete: 'delete-gallery-data',
    buskerGalleryDetail: 'busker-gallery-details',
    eventTypes: 'get-event-type',
    searchAvailBusker: 'search-available-busker',
    createUserEvent: 'create-user-event',
    buskerHireRequest: 'busker-hire-request',
    buskerHireList: 'busker-request-list',
    buskerHireAction: 'interested-notinterested-request',
    buskerNewFan: 'new-fan-start-following-me',
    buskerNewHire: 'busker-new-hire-request',
    buskerNewTip: 'busker-new-tip-recived',
    buskerNewMsg: 'busker-new-msg-notify',
    userNewPost: 'when-followed-busker-post-new-image',
    userNewEvent: 'when-followed-buske-add-new-event',
    userNewMsg: 'user-new-msg-notify',
    notificationList: 'notifications-list',
    monthyEvents: 'get-monthly-event',
    dateEventDetails: 'date-wise-event-details',
    findBuskerName: 'find-busker-by-name',
    userRecentTips: 'latest-sent-tips',
    buskerActivePayouts: 'busker-payment-account-active',
    buskerBankDetails: 'busker-bank-account-detail',
    updateBankDetails: 'add-update-busker-account-details',
    paymentDetails: 'check-busker-payment-account',
    stripeAccountStatus: 'stripe-account-status',
    buskerAddPaypal: 'create-busker-paypal-account',
    transactions: 'transactions',
    chatMessageSend: 'send-message-by-id',
    chatMessageRooms: 'get-message-room-list-by-id',
    chatMessages: 'get-all-message-by-id',
    tipCommission: 'tip-and-commission-value',
    updateFirebase: 'update-firebase-id',
    updateEvent: 'update-busker-event',
    uploadEventGallery: 'upload-event-gallery',
    deleteEventGallery: 'delete-event-gallery',
    checkDeviceToken: 'check-device-token',
    updateDeviceToken: 'update-device-token',
    logout: 'logout',
    appVersion: 'app_version',
    apiKey: 'get-api-key',
    paymentKey: 'get-payment-key',
  },
};

export default constants;
